"""empty message

Revision ID: 135acc3c5096
Revises: 
Create Date: 2020-09-18 23:18:22.315009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135acc3c5096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    artist=op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('past_shows_count', sa.Integer(), nullable=True),
    sa.Column('upcoming_shows_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    pastshows=op.create_table('pastshows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    upcommingshows=op.create_table('upcommingshows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    venue=op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('past_shows_count', sa.Integer(), nullable=True),
    sa.Column('upcoming_shows_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    past_shows_artist_assc=op.create_table('past_shows_artist_assc',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('shows_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['shows_id'], ['pastshows.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'shows_id')
    )
    past_shows_ven_assc=op.create_table('past_shows_ven_assc',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('shows_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shows_id'], ['pastshows.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'shows_id')
    )
    upcomming_shows_artist_assc=op.create_table('upcomming_shows_artist_assc',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('shows_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['shows_id'], ['upcommingshows.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'shows_id')
    )
    upcomming_shows_ven_assc=op.create_table('upcomming_shows_ven_assc',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('shows_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shows_id'], ['upcommingshows.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'shows_id')
    )
    #venue data
    data1={
        "id": 1,
        "name": "The Musical Hop",
        "genres": "Jazz, Reggae, Swing, Classical, Folk",
        "address": "1015 Folsom Street",
        "city": "San Francisco",
        "state": "CA",
        "phone": "123-123-1234",
        "website": "https://www.themusicalhop.com",
        "facebook_link": "https://www.facebook.com/TheMusicalHop",
        "seeking_talent": True,
        "seeking_description": "We are on the lookout for a local artist to play every two weeks. Please call us.",
        "image_link": "https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60",
        "past_shows": [4],
        # "past_shows": [{
        # "artist_id": 4,
        # "artist_name": "Guns N Petals",
        # "artist_image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80",
        # "start_time": "2019-05-21T21:30:00.000Z"
        # }],
        # "upcoming_shows": [],
        "upcoming_shows":[],
        "past_shows_count": 1,
        "upcoming_shows_count": 0,
    }
    data2={
        "id": 2,
        "name": "The Dueling Pianos Bar",
        "genres": "Classical, R&B, Hip-Hop",
        "address": "335 Delancey Street",
        "city": "New York",
        "state": "NY",
        "phone": "914-003-1132",
        "website": "https://www.theduelingpianos.com",
        "facebook_link": "https://www.facebook.com/theduelingpianos",
        "seeking_talent": False,
        "seeking_description":"",
        "image_link": "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80",
        "past_shows": [],
        "upcoming_shows": [],
        "past_shows_count": 0,
        "upcoming_shows_count": 0,
    }
    data3={
        "id": 3,
        "name": "Park Square Live Music & Coffee",
        "genres": "Rock n Roll, Jazz, Classical, Folk",
        "address": "34 Whiskey Moore Ave",
        "city": "San Francisco",
        "state": "CA",
        "phone": "415-000-1234",
        "website": "https://www.parksquarelivemusicandcoffee.com",
        "facebook_link": "https://www.facebook.com/ParkSquareLiveMusicAndCoffee",
        "seeking_talent": False,
        "seeking_description":"",
        "image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
        "past_shows": [5],
        "upcoming_shows":[6],
        # "past_shows": [{
        # "artist_id": 5,
        # "artist_name": "Matt Quevedo",
        # "artist_image_link": "https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        # "start_time": "2019-06-15T23:00:00.000Z"
        # }],
        # "upcoming_shows": [{
        # "artist_id": 6,
        # "artist_name": "The Wild Sax Band",
        # "artist_image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
        # "start_time": "2035-04-01T20:00:00.000Z"
        # }, {
        # "artist_id": 6,
        # "artist_name": "The Wild Sax Band",
        # "artist_image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
        # "start_time": "2035-04-08T20:00:00.000Z"
        # }, {
        # "artist_id": 6,
        # "artist_name": "The Wild Sax Band",
        # "artist_image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
        # "start_time": "2035-04-15T20:00:00.000Z"
        # }],
        "past_shows_count": 1,
        "upcoming_shows_count": 1,
    }

#artist data
    art_data1={
        "id": 4,
        "name": "Guns N Petals",
        "genres": "Rock n Roll",
        "city": "San Francisco",
        "state": "CA",
        "phone": "326-123-5000",
        "website": "https://www.gunsnpetalsband.com",
        "facebook_link": "https://www.facebook.com/GunsNPetals",
        "seeking_venue": True,
        "seeking_description": "Looking for shows to perform at in the San Francisco Bay Area!",
        "image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80",
        "past_shows": [1],
        "upcoming_shows": [],
        # "past_shows": [{
        # "venue_id": 1,
        # "venue_name": "The Musical Hop",
        # "venue_image_link": "https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60",
        # "start_time": "2019-05-21T21:30:00.000Z"
        # }],
        # "upcoming_shows": [],
        "past_shows_count": 1,
        "upcoming_shows_count": 0,
    }
    art_data2={
        "id": 5,
        "name": "Matt Quevedo",
        "genres": "Jazz",
        "city": "New York",
        "state": "NY",
        "phone": "300-400-5000",
        "website": "",
        "facebook_link": "https://www.facebook.com/mattquevedo923251523",
        "seeking_venue": False,
        "seeking_description":"",
        "image_link": "https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
        "past_shows": [3],
        "upcoming_shows": [],
        # "past_shows": [{
        # "venue_id": 3,
        # "venue_name": "Park Square Live Music & Coffee",
        # "venue_image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
        # "start_time": "2019-06-15T23:00:00.000Z"
        # }],
        # "upcoming_shows": [],
        "past_shows_count": 1,
        "upcoming_shows_count": 0,
    }
    art_data3={
        "id": 6,
        "name": "The Wild Sax Band",
        "genres": "Jazz, Classical",
        "city": "San Francisco",
        "state": "CA",
        "phone": "432-325-5432",
        "website": "",
        "facebook_link":"",
        "seeking_venue": False,
        "seeking_description":"",
        "image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
        "past_shows": [],
        "upcoming_shows": [3],
        # "past_shows": [],
        # "upcoming_shows": [{
        # "venue_id": 3,
        # "venue_name": "Park Square Live Music & Coffee",
        # "venue_image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
        # "start_time": "2035-04-01T20:00:00.000Z"
        # }, {
        # "venue_id": 3,
        # "venue_name": "Park Square Live Music & Coffee",
        # "venue_image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
        # "start_time": "2035-04-08T20:00:00.000Z"
        # }, {
        # "venue_id": 3,
        # "venue_name": "Park Square Live Music & Coffee",
        # "venue_image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
        # "start_time": "2035-04-15T20:00:00.000Z"
        # }],
        "past_shows_count": 0,
        "upcoming_shows_count": 3,
    }
    past_shows_data=[{
        "id": 1,
        "start_time":"2019-05-21T21:30:00.000Z",       
    },{
        "id": 2,
        "start_time":"2019-06-15T23:00:00.000Z",           
    }]

    past_shows_artist_assc_data=[{
        "shows_id":1,
        "artist_id":4,
    },{
        "shows_id":2,
        "artist_id":5,
    
    }]
    past_shows_ven_assc_data=[{
        "shows_id":1,
        "venue_id":1,
    },{
        "shows_id":2,
        "venue_id":3,
    }]

    upcomming_shows_data=[{
        "id": 1,
        "start_time": "2035-04-01T20:00:00.000Z",
    },{
        "id": 2,
        "start_time": "2035-04-08T20:00:00.000Z",
    },{        
        "id": 3,
        "start_time": "2035-04-15T20:00:00.000Z",
    }]
    upcomming_shows_artist_assc_data=[{
        "shows_id":1,
        "artist_id":6,
    },{
        "shows_id":2,
        "artist_id":6,
    },{
        "shows_id":3,
        "artist_id":6,
    }]
    upcomming_shows_ven_assc_data=[{
        "shows_id":1,
        "venue_id":3,
    },{
        "shows_id":2,
        "venue_id":3,
    },{
        "shows_id":3,
        "venue_id":3,
    }]

    op.bulk_insert(venue,[data1,data2,data3])
    op.bulk_insert(artist,[art_data1,art_data2,art_data3])
    op.bulk_insert(pastshows,past_shows_data)
    op.bulk_insert(upcommingshows,upcomming_shows_data)
    op.bulk_insert(past_shows_artist_assc,past_shows_artist_assc_data)
    op.bulk_insert(past_shows_ven_assc,past_shows_ven_assc_data)
    op.bulk_insert(upcomming_shows_artist_assc,upcomming_shows_artist_assc_data)
    op.bulk_insert(upcomming_shows_ven_assc,upcomming_shows_ven_assc_data)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcomming_shows_ven_assc')
    op.drop_table('upcomming_shows_artist_assc')
    op.drop_table('past_shows_ven_assc')
    op.drop_table('past_shows_artist_assc')
    op.drop_table('venue')
    op.drop_table('upcommingshows')
    op.drop_table('pastshows')
    op.drop_table('artist')
    # ### end Alembic commands ###
